# Generated by Django 3.0.3 on 2020-03-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chancePyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='round',
            new_name='round_nr',
        ),
        migrations.RemoveField(
            model_name='game',
            name='swag',
        ),
    ]
