# Generated by Django 3.0.3 on 2020-03-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chancePyApp', '0002_auto_20200304_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='visited_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='visitors_players',
        ),
    ]
